version: '3.9'
services:
  ec-api:
    image: registry.cn-hangzhou.aliyuncs.com/kami1983/ec_api:latest
    container_name: ec-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/home/node/app/.env
      - ./data:/home/node/app/data
